# Layout::AlignArray
#
# Check if elements of a multi-line array literal are aligned.

Layout/AlignArray:
  Enabled: false

# Layout::AlignHash
#
# Check if the keys, separators, and values of a multi-line hash literal are aligned.

Layout/AlignHash:
  Enabled: false

# Layout::AlignParameters
#
# Check if parameters on a multi-line method call or definition are aligned.

Layout/AlignParameters:
  Enabled: false

# Layout::BlockAlignment
#
# Checks whether the end keywords are aligned properly for do end blocks.
#
# The value `start_of_block` means that the `end` should be aligned with line
# where the `do` keyword appears.
#
# The value `start_of_line` means it should be aligned with the whole
# expression's starting line.
#
# The value `either` means both are allowed.

Layout/BlockAlignment:
  EnforcedStyleAlignWith: either


# Layout::ConditionPosition
#
# Checks for conditions that are not on the same line as if/while/until.
#
# bad:
#
#   if
#     some_condition
#     do_something
#   end
#
# good:
#
#   if some_condition
#     do_something
#   end
#
  
Layout/ConditionPosition:
  Enabled: false

# Layout::CommentIndentation
#
# Checks the indentation of comments.

Layout/CommentIndentation:
  Enabled: false

# Layput::DefEndAlignment
#
# Checks whether the end keywords of method definitions are aligned properly

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: true

# Layout::DotPosition
#
# Checks the '.' position in multi-line method calls

Layout/DotPosition:
  EnforcedStyle: trailing

# Layout::EndAlignment
#
# Checks whether the end keywords are aligned properly

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword
  AutoCorrect: true

# Layout::EndOfLine
#
# Checks for Windows-style line endings in source code.

Layout/EndOfLine:
  Enabled: false

# Layout::FirstArrayElementLineBreak
#
# Checks for a line break before the first element in a multi-line array.
#
# bad:
#
#  [ :a,
#    :b]
#
# good:
#
#  [
#    :a,
#    :b]

Layout/FirstArrayElementLineBreak:
  Enabled: false

# Layout::FirstHashElementLineBreak
#
# Checks for a line break before the first element in a multi-line hash.
#
# bad:
#
#  { a: 1,
#    b: 2}
#
# good:
#
#  {
#    a: 1,
#    b: 2 }

Layout/FirstHashElementLineBreak:
  Enabled: false

# Layout::ExtraSpacing
#
# Checks for extra/unnecessary whitespace

Layout/ExtraSpacing:
  # When true, allows most uses of extra spacing if the intent is to align
  # things with the previous or next line, not counting empty lines or comment
  # lines.
  AllowForAlignment: true
  # When true, forces the alignment of `=` in assignments on consecutive lines.
  ForceEqualSignAlignment: false

# Layout::IndentAssignment
#
# Checks the indentation of the first line of the right-hand-side of a multi-line assignment.
#
# bad:
#
#  value =
#  if foo
#    'bar'
#  end
#
# good:
#
#  value =
#    if foo
#    'bar'
#  end

Layout/IndentAssignment:
  Enabled: false

# Layout::IndentationConsistency
#
# Checks for inconsistent indentation
#
# bad:
#
#   def test
#     puts "world"
#       puts "here"
#   end

Layout/IndentationConsistency:
  EnforcedStyle: normal

# Layout::IndentationWidth
#
# Checks for indentation that does't use two spaces
#
# bad:
#
#   def test
#    puts "world"
#   end

Layout/IndentationWidth:
  Width: 2
  IgnoredPatterns: []

# StLayoutyle::EmptyLinesAroundAccessModifier
#
# Access modifiers should be surrounded by blank spaces.

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

# Layout::EmptyLinesAroundBlockBody
#
# Checks if empty lines around the bodies of blocks match the configuration.
#
# bad:
#
#  foo do |bar|
#    ...
#  end
#
# good:
#
#  foo do |bar|
#
#    ....
#
#  end
#
# ( This helps in readability of code )

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Layout::EmptyLinesAroundClassBody
#
# Checks if empty lines around the bodies of classes match the configuration

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Layout::EmptyLinesAroundMethodBody
#
# Checks if empty lines exist around the bodies of methods.

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

# Layout::EmptyLinesAroundModuleBody
#
# Checks if empty lines around the bodies of modules match the configuration

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Layout::CaseIndentation
#
# Checks how the 'when's of a case expression are indented in relation to its
# 'case' or 'end' keyword
#
# bad:
#
#  case foo
#    when *condition
#     bar
#   when baz
#     foobar
#  end
#
# good:
#
#  case foo
#  when baz
#    foobar
#  when *condition
#    bar
#  end

Layout/CaseIndentation:
  Enabled: false

# Layout::IndentFirstArgument
#
# Checks the indentation of the first parameter in a method call.
# ( This cop checks only for first parameter indentation )
# bad:
#
#  some_method(
#  first_param,
#  second_param)
#
# good:
#
#  some_method(
#    first_param,
#  second_param)

Layout/IndentFirstArgument:
  EnforcedStyle: special_for_inner_method_call_in_parentheses

# Layout::IndentFirstArrayElement
#
# Checks for indentation of the first element in the array literal where
# the opening bracket and the first elements are on separate lines.
# ( Array literals shall have their first element indented one step (2 spaces)
#   more than the start of the line where the opening bracket is )

Layout/IndentFirstArrayElement:
  Enabled: false

# Layout::IndentFirstHashElement
#
# Same as the Indent Array but in case of hash

Layout/IndentFirstHashElement:
  Enabled: false

# Layout::MultilineArrayBraceLayout
#
# Checks that the closing brace in an array literal is either on the
# same line as the last array element, or a new line.
#
# symmetrical: closing brace is positioned in same way as opening brace

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical

# Layout::MultilineAssignmentLayout
#
# Checks whether the multiline assignments have a new line after
# the assignment operator
#
# bad: (with EnforcedStyle set to new_line)
#
#  foo = if expression
#    'bar'
#  end
#
# good: (with EnforcedStyle set to same_line)
#
#  foo = if expression
#    'bar'
#  end

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

# Layout::MultilineHashBraceLayout
#
# Checks that the closing brace in a hash literal is either on the
# same line as the last hash element, or a new line
#
# Symmetrical:
#   { a: 1,
#     b: 2 }
#
#   {
#     a: 1,
#     b: 2
#   }

Layout/MultilineHashBraceLayout:
  EnforcedStyle: symmetrical

# Layout::MultilineMethodCallBraceLayout
#
# Checks that the closing brace in a method call is either on the
# same line as the last method argument, or a new line

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: symmetrical

# Layout::MultilineMethodCallIndentation
#
# Checks the indentation of the method name part in method calls
# that span more than one line.
#
# bad
#  while a
#  .b
#    something
#  end
#
# good:
#
#  while a
#        .b
#    something
#  end

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

# Layout::MultilineMethodDefinitionBraceLayout
#
# Checks that the closing brace in a method definition is either on the
# same line as the last method parameter, or a new line

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: symmetrical

# Layout::MultilineOperationIndentation
#
# Checks the indentation of the right hand side operand in the binary operations that span
# more than one line.
#
# bad:
#
#  if a +
#  b
#    something
#  end

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

# Layout::SpaceAroundEqualsInParameterDefault
#
# Checks that the equals signs in parameter default assignments have surrounding space

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

# Layout::SpaceBeforeBlockBraces
#
# Checks that block braces have/dont have space before the opening brace depending on configuration
Layout/SpaceBeforeBlockBraces:
  Enabled: false

# Layout::SpaceBeforeComment
#
# Checks for missing space between a token and comment on the same line.

Layout/SpaceBeforeComment:
  Enabled: false

# Layout::SpaceInLambdaLiteral
#
# Checks for spaces between -> and opening parameter brace in lambda literals
#
# bad:  a = ->(x,y) { x + y }
#
# good: a = -> (x,y) { x + y }

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

# Layout::SpaceInsideBlockBraces
#
# Checks that block braces have or don't have surrounding space inside them on configuration
Layout/SpaceInsideBlockBraces:
  Enabled: false

# Layout::SpaceInsideHashLiteralBraces
#
# Checks that braces used for hash literals have or
# don't have surrounding space depending on configuration.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Layout::SpacsInsideParens
#
# Checks for spaces inside ordinary round parenthesis
Layout/SpaceInsideParens:
  Enabled: false

# Layout::SpaceInsideStringInterpolation
#
# Checks for whitespace withing string interpolations.
#
# bad: "#{no_space}"
#
# good: "#{ space }"

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

# Layout::Tab
#
# Checks for tabs inside the source code
Layout/Tab:
  Enabled: false

# Layout::TrailingWhitespace
#
# Checks for trailing whitespace in the source code
Layout/TrailingWhitespace:
  Enabled: false