# Naming::AccessorMethodName
#
# Makes sure that accessor methods are named properly
#
# bad:
#
#   def set_attribute(value)..
#   def get_attribute
#
# good:
#
#   def attribute=(value)..
#   def attribute...
#
Naming/AccessorMethodName:
  Enabled: true

# Naming::ClassAndModuleCamelCase
#
# Checks for class and module names with an underscore in them

Naming/ClassAndModuleCamelCase:
  Enabled: true


# Naming::FileName
#
# Makes sure that Ruby source files have snake_case names.

Naming/FileName:
  Enabled: true

# Naming::MethodName
#
# Makes sure that all methods use the 'snake_case' for their name.

Naming/MethodName:
  EnforcedStyle: snake_case


# Naming::ConstantName
#
# Checks for 'snake_case' is used or not for naming Constants

Naming/ConstantName:
  Enabled: true

# Naming::PredicateName
#
# Makes sure that predicates are named properly.
#
# bad:   def is_even?(value)
#
# good:  def even?(value)
Naming/PredicateName:
  Enabled: true

# Naming::VariableName
#
# Makes sure that all the variables use the configured style : snake_case
Naming/VariableName:
  EnforcedStyle: snake_case

# Naming::VariableNumber
#
# Makes sure that all numbered variables use the snake_case  style, for their numbering
Naming/VariableNumber:
  EnforcedStyle: snake_case

# Naming::BinaryOperatorParameterName
#
# Makes sure that certain operator method have their sole parameter named `other`
Naming/BinaryOperatorParameterName:
  Enabled: false